### ISSUE TITLE
Can't type Vietnamese words when delete to the beginning of line

### ISSUE THREAD

**Issue by pirackr** [pirackr/Sublime-Bogo#15]
Reproduce:

```
- Write a long line, like: "không thể nào được như vậy"
- Delete all the line, then start typing it again
=> We can't type Vietnamese for first word.
```

**Comment by lewtds** [comment]
Cannot reproduce.

**Comment by pirackr** [comment]
@lewtds try this:
- Typing: "không thể nào được như vậy"
- Press `Shift + Home`, then `Backspace`
- Then try to type: "không"

Do it once or twice, you won't get "không", just "khoong"

**Comment by lewtds** [comment]
Probably a pre-#18 behavior. Still can't reproduce.

**Comment by pirackr** [comment]
Let me test it again.

**Comment by pirackr** [comment]
It's only happened on ST2, may be it's ST2 bugs, not us.
