### ISSUE TITLE
Wrong result when deleting some characters and continue typing

### ISSUE THREAD

**Issue by tiev** [pirackr/Sublime-Bogo#16]
I'm on Sublime Text 3 - Ubuntu.
When I finish typing 'truyền'
I delete back until 'truy', and start typing e-e-n-j to get truyện. But the result is 'truyỵen'.

Also, when I type 'trụy' normally, it's ok. But if I have typed 'truy', somehow I want to change it to 'trụy', and if I put the cursor at \* position 'tru*y', it turn into 'tụyy'

**Comment by pirackr** [comment]
It's good now. Both tested on ST2 and ST3.
