### ISSUE TITLE
Immediately mark an opened file as pending changes

### ISSUE THREAD

**Issue by tiev** [pirackr/Sublime-Bogo#17]
When enable bogo (Alt + Z), if I open a new file (by Sidebar or Ctrl+P), the file is immediately marked as pending changes (round symbol at file's close button)

**Comment by lewtds** [comment]
Probably a side effect of #14. Should be fixed with #18.

**Comment by lewtds** [comment]
Please check again with the latest version.

**Comment by tiev** [comment]
Yes, it's fixed

**Comment by pirackr** [comment]
Ok, tks @tiev and @lewtds
