### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by lewtds** [pirackr/Sublime-Bogo#19]
No FOSS project should go without a FOSS license.

**Comment by pirackr** [comment]
Hi @lewtds , I suggest GPLv3 or MIT but don't know if it's good enough or compatible with Bogo-Python engine or not?

**Comment by lewtds** [comment]
GPLv3 should do fine. On the other hand, MIT would not be possible as bogo-python is GPLv3-licensed and you cannot include more restrictive licensed code inside more liberal code (only in the other direction).
