### ISSUE TITLE
Doesn't work with multicursors

### ISSUE THREAD

**Issue by lewtds** [pirackr/Sublime-Bogo#3]
The plugin doesn't process user input when multiple cursors are used.

**Comment by pirackr** [comment]
91a06b3131d2da463a981a1b8cbb5e90512742c3

**Comment by lewtds** [comment]
Still not working with the latest commit. Please reopen.

**Comment by pirackr** [comment]
@lewtds : please recheck this issue. I can't reproduce the issue, it's still working on my laptop.

**Comment by lewtds** [comment]
Fixed in #12.
