### ISSUE TITLE
Không chuyển được kiểu gõ khi cài qua package control

### ISSUE THREAD

**Issue by jaredchu** [pirackr/Sublime-Bogo#31]
Với ST3, cài Sublime-Bogo không chuyển được kiểu gõ từ Telex sang Vni qua User setting.

**Comment by pirackr** [comment]
@hienboy90 : VNI and Telex typing method is implemented in the very first version of this plugin but since we have a big refactor then it is currently disabled, I will re-implement it and fix the autocompletion bug later (too busy now, sorry). Thanks for reporting.
