### ISSUE TITLE
We crash plugin_host when typing in a new document

### ISSUE THREAD

**Issue by lewtds** [pirackr/Sublime-Bogo#7]
Intermitten bug. Not really sure how to trigger.

**UPDATE**
It happens whenever we switch to another document and start typing.

**Comment by pirackr** [comment]
lewtds https://github.com/pirackr/Sublime-Bogo/issues/5, is it?

**Comment by lewtds** [comment]
Not sure. Can't see any trace in the ST console.

**Comment by lewtds** [comment]
OK. It can be triggered by the following sequence:
- Open ST3
- Create a new tab with Ctrl+N
- Type in "cas meof"

The plugin_host should crash right after "cá" with the following message in the console:

> error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted

**Comment by pirackr** [comment]
OK, let me check it.

**Comment by lewtds** [comment]
It happens whenever we switch to another document and start typing.

**Comment by pirackr** [comment]
@lewtds : please update the source code and check it again, I think d9b42ac85cc3e85ca35d6a0668034c5e69a595a1 should fix both #7 and #5

**Comment by lewtds** [comment]
Confirm for #7. I don't have ST2 here to check #5 though. Good work!
