### ISSUE TITLE
Distribute on Package Control

### ISSUE THREAD

**Issue by lewtds** [pirackr/Sublime-Bogo#8]
This is how to submit a package: https://sublime.wbond.net/docs/submitting_a_package

**Comment by lewtds** [comment]
Pull request to add on PC: https://github.com/wbond/package_control_channel/pull/3382

**Comment by pirackr** [comment]
Nice, tks @lewtds

**Comment by lewtds** [comment]
Done :dancers: 

https://sublime.wbond.net/packages/BoGo
